
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kjer-si
resources:
  - postgis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
- name: kjer-si
  newName: rg.fr-par.scw.cloud/djnd/kjer.si
  newTag: '907f06d8bf1eb6de618087431346db1c43e44eb0'
