version: '3.7'

services:
  phoenix:
    build: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: kjer_si
      PGPORT: 5432
      PGHOST: db
      SECRET_KEY: ThisShouldBeSomethingSecret
      HOST: localhost
      MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - db
    # working_dir: /app
    volumes:
      - .:/app/
    #   - elixir-deps:/app/deps/
    #   - elixir-build:/app/_build/
    # command: >
    #   /bin/sh -c 'apt-get update && apt-get install -y inotify-tools'
    # entrypoint:
    #   ./entrypoint.sh

  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kjer_si
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  # elixir-deps:
  # elixir-build:
