version: '3.7'

services:
  phoenix:
    image: elixir:latest
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: kjer_si
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app/:ro
      - elixir-deps:/app/deps/
      - elixir-build:/app/_build/
    command: >
      /bin/sh -c 'apt-get update && apt-get install -y inotify-tools &&
      mix local.hex --force &&
      mix local.rebar --force &&
      mix deps.get &&
      mix ecto.setup &&
      mix phx.server'

  db:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  elixir-deps: {}
  elixir-build: {}
