name: Elixir CI

on: push

jobs:
  format-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.10.2 # Define the elixir version [required]
          otp-version: 22.3 # Define the OTP version [required]
      - name: Install Dependencies
        working-directory: backend
        run: mix deps.get
      - name: Check Formatting
        working-directory: backend
        run: mix format --check-formatted
      - name: Run Tests
        working-directory: backend
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          SECRET_KEY: FakeSecretForTests
          PGDATABASE: kjer_si
          PGHOST: localhost
        run: mix test
